In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
movie = pd.read_csv("Data/tmdb_5000_movies.csv") #Load movie data set 
credit =  pd.read_csv("Data/tmdb_5000_credits.csv") #Load credit dataset

In [3]:
movie.sample(10)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
331,95000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://www.seventhsonmovie.com/,68737,"[{""id"": 2343, ""name"": ""magic""}, {""id"": 4238, ""...",en,Seventh Son,"John Gregory, who is a seventh son of a sevent...",63.628459,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""CN"", ""name"": ""China""}, {""iso_...",2014-12-12,114178613,102.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"When darkness falls, the son will rise. When t...",Seventh Son,5.2,957
2685,14000000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 53, ""nam...",NaN,11586,"[{""id"": 2626, ""name"": ""exorcism""}, {""id"": 4793...",en,Exorcist II: The Heretic,Bizarre nightmares plague Regan MacNeil four y...,11.543363,"[{""name"": ""Warner Bros."", ""id"": 6194}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1977-06-17,30749142,118.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,It's four years later... what does she remember?,Exorcist II: The Heretic,4.5,133
2335,18000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,160588,"[{""id"": 582, ""name"": ""san francisco""}, {""id"": ...",en,Blue Jasmine,Jasmine French used to be on the top of the he...,34.694216,"[{""name"": ""Perdido Productions"", ""id"": 12966}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-07-25,99206215,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Blue Moon. I used to know the words. Now they'...,Blue Jasmine,7.0,1098
1720,28000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,23483,"[{""id"": 853, ""name"": ""crime fighter""}, {""id"": ...",en,Kick-Ass,Dave Lizewski is an unnoticed high school stud...,45.054936,"[{""name"": ""Lionsgate"", ""id"": 1632}, {""name"": ""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2010-03-22,96188903,117.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Shut up. Kick ass.,Kick-Ass,7.1,4645
2300,19000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 36, ""name...",NaN,17277,"[{""id"": 1405, ""name"": ""roman empire""}, {""id"": ...",en,The Fall of the Roman Empire,Drawn from the same events that later inspired...,4.229942,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1964-03-24,4750000,188.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Most Magnificent Re-Creation . . . Of An A...,The Fall of the Roman Empire,6.0,33
4661,245000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",NaN,3060,"[{""id"": 2504, ""name"": ""world war i""}, {""id"": 1...",en,The Big Parade,The story of an idle rich boy who joins the US...,0.785744,"[{""name"": ""Metro-Goldwyn-Mayer (MGM)"", ""id"": 8...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1925-11-05,22000000,151.0,[],Released,NaN,The Big Parade,7.0,21
538,52000000,"[{""id"": 9648, ""name"": ""Mystery""}, {""id"": 18, ""...",NaN,2026,"[{""id"": 1812, ""name"": ""fbi""}, {""id"": 1930, ""na...",en,Hostage,When a mafia accountant is taken hostage on hi...,23.663713,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...",2005-03-09,77944725,113.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Every Second Counts,Hostage,6.2,512
2372,0,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",NaN,27380,"[{""id"": 407, ""name"": ""dictator""}, {""id"": 13065...",en,Megaforce,Megaforce is an elite multi-national military ...,1.110179,"[{""name"": ""Golden Harvest Company"", ""id"": 2521...","[{""iso_3166_1"": ""HK"", ""name"": ""Hong Kong""}, {""...",1982-06-25,0,99.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Deeds not Words,Megaforce,3.5,15
4182,0,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",http://www.travellersandmagicians.com/,37232,"[{""id"": 4662, ""name"": ""illusion""}, {""id"": 1018...",en,Travellers and Magicians,"A young government official, named Dondup, who...",0.749699,"[{""name"": ""Prayer Flag Pictures"", ""id"": 72591}]","[{""iso_3166_1"": ""BT"", ""name"": ""Bhutan""}, {""iso...",2003-09-09,0,108.0,"[{""iso_639_1"": ""dz"", ""name"": """"}]",Released,The bitter and the sweet of temporary things.,Travellers and Magicians,6.8,9
3897,3000000,"[{""id"": 35, ""name"": ""Comedy""}]",NaN,20337,"[{""id"": 1850, ""name"": ""daily life""}, {""id"": 36...",en,Martin Lawrence Live: Runteldat,The controversial bad-boy of comedy delivers a...,0.295226,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2002-08-01,19184015,113.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Martin Lawrence Live: Runteldat,5.0,1

In [4]:
credit.sample(10)

,movie_id,title,cast,crew
3944,11229,Freeway,"[{""cast_id"": 1, ""character"": ""Bob Wolverton"", ...","[{""credit_id"": ""52fe44169251416c750285b5"", ""de..."
497,9533,Red Dragon,"[{""cast_id"": 1, ""character"": ""Hannibal Lecter""...","[{""credit_id"": ""52fe4505c3a36847f80b7b55"", ""de..."
4368,9707,Bubba Ho-tep,"[{""cast_id"": 1, ""character"": ""Elvis"", ""credit_...","[{""credit_id"": ""52fe451fc3a36847f80bdd31"", ""de..."
4067,69640,Lies in Plain Sight,"[{""cast_id"": 3, ""character"": ""Sofia Delgado"", ...","[{""credit_id"": ""59537e6ec3a36814ae039978"", ""de..."
1398,13051,Max Payne,"[{""cast_id"": 1, ""character"": ""Max Payne"", ""cre...","[{""credit_id"": ""52fe45339251416c7504eee5"", ""de..."
2979,1588,Bring It On,"[{""cast_id"": 1, ""character"": ""Torrance Shipman...","[{""credit_id"": ""5378329bc3a3685554003073"", ""de..."
443,10202,Bedtime Stories,"[{""cast_id"": 2, ""character"": ""Skeeter Bronson""...","[{""credit_id"": ""52fe43409251416c750095a9"", ""de..."
2356,22327,Youth in Revolt,"[{""cast_id"": 1, ""character"": ""Nick Twisp"", ""cr...","[{""credit_id"": ""58b987f1c3a368663000abc3"", ""de..."
1520,124459,The Incredible Burt Wonderstone,"[{""cast_id"": 5, ""character"": ""Burt Wonderstone...","[{""credit_id"": ""5640b21992514170610013a4"", ""de..."
642,227306,Unbroken,"[{""cast_id"": 11, ""character"": ""Louis Zamperini...","[{""credit_id"": ""531b62dd92514177b1004164"", ""de..."

In [5]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [6]:
credit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [7]:
credit.shape,movie.shape  # Finding shape of both data frame.

((4803, 4), (4803, 20))

In [8]:
merge_dataset = movie.merge(credit,on='title') #Merging two data set in one.

In [9]:
merge_dataset.sample(10) #Giving sample data points of merge dataset.

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
838,50000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",NaN,8077,"[{""id"": 378, ""name"": ""prison""}, {""id"": 803, ""n...",en,Alien³,After escaping with Newt and Hicks from the al...,45.856409,"[{""name"": ""Twentieth Century Fox Film Corporat...",...,114.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The bitch is back.,Alien³,6.2,1633,8077,"[{""cast_id"": 1, ""character"": ""Ripley"", ""credit...","[{""credit_id"": ""53944156c3a3686434002af5"", ""de..."
1073,45000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 35, ""...",NaN,17379,[],en,Last Holiday,"After she's diagnosed with a terminal illness,...",6.156015,"[{""name"": ""Paramount Pictures"", ""id"": 4}]",...,112.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,She always thought she was somebody special......,Last Holiday,6.4,119,17379,"[{""cast_id"": 1, ""character"": ""Georgia Byrd"", ""...","[{""credit_id"": ""52fe47229251416c7508ec43"", ""de..."
4554,500000,"[{""id"": 18, ""name"": ""Drama""}]",NaN,81220,"[{""id"": 10183, ""name"": ""independent film""}]",en,Everything Put Together,Everything Put Together is a 2000 film directe...,0.046903,"[{""name"": ""Furst Films"", ""id"": 3135}]",...,87.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Everything Put Together,5.0,2,81220,"[{""cast_id"": 4, ""character"": """", ""credit_id"": ...","[{""credit_id"": ""52fe48019251416c9107ce43"", ""de..."
1867,0,"[{""id"": 35, ""name"": ""Comedy""}]",NaN,10735,"[{""id"": 212, ""name"": ""london england""}, {""id"":...",en,What a Girl Wants,"An American girl, Daphne, heads to Europe in s...",7.057765,"[{""name"": ""DiNovi Pictures"", ""id"": 813}, {""nam...",...,105.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Trying to fit in. Born to stand out.,What a Girl Wants,5.8,368,10735,"[{""cast_id"": 1, ""character"": ""Daphne Reynolds""...","[{""credit_id"": ""52fe43ac9251416c750199df"", ""de..."
4713,0,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 18, ""n...",NaN,50497,"[{""id"": 918, ""name"": ""newspaper""}, {""id"": 2626...",en,When the Lights Went Out,"Yorkshire, 1974, the Maynard family moves into...",2.805351,"[{""name"": ""Kintop Pictures"", ""id"": 1490}]",...,86.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Set in 1974 and based on true events.,When the Lights Went Out,5.8,49,50497,"[{""cast_id"": 1, ""character"": ""Jenny"", ""credit_...","[{""credit_id"": ""538746190e0a26144d003d19"", ""de..."
4376,1000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",NaN,26791,[],en,Brigham City,Wes Clayton is a lawman and a bishop in a Morm...,0.280083,"[{""name"": ""Main Street Movie Company"", ""id"": 6...",...,119.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Brigham City,7.3,4,26791,"[{""cast_id"": 3, ""character"": ""Sheriff"", ""credi...","[{""credit_id"": ""52fe4519c3a368484e0485cb"", ""de..."
839,55000000,"[{""id"": 36, ""name"": ""History""}, {""id"": 18, ""na...",http://en.wikipedia.org/wiki/Evita_(film),8818,"[{""id"": 549, ""name"": ""prostitute""}, {""id"": 165...",en,Evita,The hit musical based on the life of Evita Dua...,7.027139,"[{""name"": ""Hollywood Pictures"", ""id"": 915}, {""...",...,134.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The Most Anticipated Motion Picture Event of T...,Evita,5.9,120,8818,"[{""cast_id"": 1, ""character"": ""Eva Per\u00f3n"",...","[{""credit_id"": ""52fe44bac3a36847f80a6c53"", ""de..."
817,55000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,8273,"[{""id"": 772, ""name"": ""handcuffs""}, {""id"": 1156...",en,American Wedding,"With high school a distant memory, Jim and Mic...",36.194802,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",...,103.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Forever hold your piece.,American Wedding,6.0,1129,8273,"[{""cast_id"": 7, ""character"": ""Jim Levenstein"",...","[{""credit_id"": ""52fe449ac3a36847f809f9a1"", ""de..."
2994,10000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 35, ""...",http://www.billandted.org/,1648,"[{""id"": 931, ""name"": ""jealousy""}, {""id"": 1743,...",en,Bill & Ted's Excellent Adventure,"In the small town of San Dimas, a few miles aw...",25.929893,"[{""name"": ""Orion Pictures"", ""id"": 41}]",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,History is about to be rewritten by two guys w...,Bill & Ted's Excellent Adventure,6.7,454,1648,"[{""cast_id"": 1, ""character"": ""Ted Logan"", ""cre...","[{""credit_id"": ""52fe4308c3a36847f8035623"", ""de..."
1104,44000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",NaN,5503,"[{""id"": 520, ""name"": ""chicago""}, {""id"": 797, ""...",en,The Fugitive,"Wrongfully accused of murdering his wife, Rich...",54.884297,"[{""name"": ""Warner Bros."", ""id"": 6194}]",...,130.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A murdered wife. A one-armed man. An obsessed ...,The Fugitive,7.2,1220,5503,"[{""cast_id"": 2, ""character"": ""Dr. Kimble"", ""cr...","[{""credit_id"": ""52fe440ac3a36847f807eb7f"", ""de..."

In [10]:
merge_dataset.shape   #Counting the shape of merge dataset.

(4809, 23)

In [11]:
movie["original_language"].value_counts() #Counting language

original_language
en    4505
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
cn      12
ko      11
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
id       2
cs       2
ta       2
ro       2
ar       2
te       1
hu       1
xx       1
af       1
is       1
tr       1
vi       1
pl       1
nb       1
ky       1
no       1
sl       1
ps       1
el       1
Name: count, dtype: int64

In [12]:
merge_dataset.columns # Return all the colmn from movie.

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [13]:
merge_dataset =merge_dataset[["genres","original_language","original_title","overview","popularity","cast","crew","keywords"]] #Extracting important column that we want to do prediction.

#Preprocessing the data/ Removing the empty column

In [14]:
merge_dataset.isnull().sum()

genres               0
original_language    0
original_title       0
overview             3
popularity           0
cast                 0
crew                 0
keywords             0
dtype: int64

In [15]:
merge_dataset.dropna(inplace=True)  # Only three null value therefor we drop that data point.

In [16]:
merge_dataset

,genres,original_language,original_title,overview,popularity,cast,crew,keywords
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."
...,...,...,...,...,...,...,...,...
4804,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...","[{""id"": 5616, ""name"": ""united states\u2013mexi..."
4805,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...",[]
4806,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam..."
4807,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",[]
4808,"[{""id"": 99, ""name"": ""Documentary""}]",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224..."

In [17]:
merge_dataset.shape

(4806, 8)

In [18]:
type(merge_dataset['genres'][0]) #We cant't perform operation on str.

str

In [19]:
import ast # Help to convert str to list

In [20]:
def converter(text,keyword='name'): #Function that convert the str to list using ast.
    l=[]
    for i in ast.literal_eval(text): #apply loop to extract the str frome dataset and convert it into list
        l.append(i[keyword]) #Appending name from the list of dictionary.

    return l

In [21]:
# Applying the convert function on the column.
merge_dataset['genres'] = merge_dataset['genres'].apply(converter)

In [22]:
merge_dataset.sample(5) # Sample of the updated column.

,genres,original_language,original_title,overview,popularity,cast,crew,keywords
1081,"[Adventure, Drama, Music, Romance]",en,Across the Universe,Musical based on The Beatles songbook and set ...,11.872841,"[{""cast_id"": 11, ""character"": ""Lucy Carrigan"",...","[{""credit_id"": ""52fe43d3c3a36847f8072939"", ""de...","[{""id"": 2187, ""name"": ""riot""}, {""id"": 4108, ""n..."
2126,"[Drama, Crime, Thriller]",en,Lakeview Terrace,A young interracial couple has just moved into...,20.495749,"[{""cast_id"": 26, ""character"": ""Abel Turner"", ""...","[{""credit_id"": ""52fe45559251416c75052f31"", ""de...","[{""id"": 2016, ""name"": ""vandalism""}, {""id"": 253..."
2629,"[Thriller, Drama, Mystery]",en,Mulholland Drive,After a car wreck on the winding Mulholland Dr...,31.609850,"[{""cast_id"": 8, ""character"": ""Betty Elms"", ""cr...","[{""credit_id"": ""52fe42e4c3a36847f802aea5"", ""de...","[{""id"": 222, ""name"": ""schizophrenia""}, {""id"": ..."
1152,"[Crime, Drama, Mystery, Thriller]",en,Double Jeopardy,A woman framed for her husband's murder suspec...,19.439386,"[{""cast_id"": 1, ""character"": ""Travis Lehman"", ...","[{""credit_id"": ""52fe43679251416c7500eef9"", ""de...","[{""id"": 378, ""name"": ""prison""}, {""id"": 544, ""n..."
1359,"[Adventure, Comedy, Crime, Science Fiction]",en,Austin Powers: The Spy Who Shagged Me,"When diabolical genius, Dr. Evil travels back ...",18.316151,"[{""cast_id"": 25, ""character"": ""Austin Powers /...","[{""credit_id"": ""52fe427bc3a36847f8022011"", ""de...","[{""id"": 83, ""name"": ""saving the world""}, {""id""..."

In [23]:
merge_dataset["keywords"][0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [24]:
merge_dataset["keywords"] = merge_dataset["keywords"].apply(converter)

In [25]:
merge_dataset["cast"][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [26]:
merge_dataset['cast'] = merge_dataset['cast'].apply(lambda x: converter(x,keyword = "character"))

In [27]:
merge_dataset.sample(5)

,genres,original_language,original_title,overview,popularity,cast,crew,keywords
916,[Comedy],en,Daddy's Home,The story of a mild-mannered radio executive (...,38.616744,"[Brad Whitaker, Dusty Mayron, Sara Whitaker, L...","[{""credit_id"": ""56edb908c3a3682253008126"", ""de...",[daddys home]
1403,"[Comedy, Drama, Romance]",en,Something Borrowed,Though Rachel (Ginnifer Goodwin) is a successf...,14.029012,"[Darcy, Rachel, Ethan, Dex, Claire, Marcus, Br...","[{""credit_id"": ""556094369251417e51005e8e"", ""de...","[new york, alcohol, based on novel, secret, ch..."
2099,"[Adventure, Comedy, Family, Romance]",en,Are We There Yet?,"The fledgling romance between Nick, a playboy ...",13.590677,"[Nick Persons, Suzanne Kingston, Lindsey Kings...","[{""credit_id"": ""5539fe07c3a3684022000d96"", ""de...","[car journey, macho, road trip, children, pret..."
1206,"[Drama, Horror, Mystery, Thriller]",en,The Skeleton Key,A hospice nurse working at a spooky New Orlean...,29.105407,"[Caroline Ellis, Violet Devereaux, Luke Marsha...","[{""credit_id"": ""52fe4547c3a36847f80c53c7"", ""de...","[nurse, secret, dream, fight, kidnapping, new ..."
1834,"[Comedy, Drama, Romance]",en,Chocolat,A fable of emotional liberation and chocolate....,28.727731,"[Vianne Rocher, Comte Paul de Reynaud, Roux, A...","[{""credit_id"": ""52fe423ec3a36847f800eefb"", ""de...","[chocolate, mayor, praline, single, mother dau..."

In [28]:
merge_dataset['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [29]:
def fetch_director(text):
    l=[]
    for i in ast.literal_eval(text):
        if(i['job'] == "Director"):
            l.append(i['name'])
            break
    return l

In [30]:
merge_dataset['crew'] = merge_dataset['crew'].apply(fetch_director)

In [31]:
merge_dataset.sample(5)

,genres,original_language,original_title,overview,popularity,cast,crew,keywords
2513,"[Comedy, Family]",en,Home Alone,Eight-year-old Kevin McCallister makes the mos...,2.186927,"[Kevin, Harry, Marv, Peter, Kate, Marley, Buzz...",[Chris Columbus],"[holiday, burglar, home invasion, mischief, bo..."
107,"[Action, Adventure, Fantasy]",en,Warcraft,The peaceful realm of Azeroth stands on the br...,63.148529,"[Garona Halforcen, Anduin Lothar, Medivh, Orgr...",[Duncan Jones],"[video game, elves, orcs, magic, chase, based ..."
935,"[Comedy, Family, Adventure, Fantasy, Romance]",en,Herbie Fully Loaded,"Maggie Peyton, the new owner of Number 53 - th...",12.050755,"[Maggie Peyton, Ray Peyton Sr., Trip Murphy, R...",[Angela Robinson],"[car race, victory, car, nascar, woman director]"
4320,[],en,Crowsnest,"In late summer of 2011, five young friends on ...",0.057564,[],[],[]
2008,[Drama],en,The End of the Affair,"On a rainy London night in 1946, novelist Maur...",6.921263,"[Maurice Bendrix, Henry Miles, Sarah Miles, Mr...",[Neil Jordan],"[bomb, sex, jealousy, infidelity, obsession, w..."

In [32]:
#Converting the overview to list
merge_dataset["overview"] = merge_dataset["overview"].apply(lambda x:x.split())

In [33]:
merge_dataset["overview"][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

In [34]:
# Function to remove extra space from the list.
def remove_space(word):
    l = []
    for i in word:
        l.append(i.replace(" ","")) #Replace space 
    return l

In [35]:
merge_dataset['cast'] = merge_dataset['cast'].apply(remove_space)
merge_dataset['crew'] = merge_dataset['crew'].apply(remove_space)
merge_dataset['genres'] = merge_dataset['genres'].apply(remove_space)
merge_dataset['crew'] = merge_dataset['crew'].apply(remove_space)
merge_dataset['keywords'] = merge_dataset['keywords'].apply(remove_space)

In [36]:
merge_dataset.sample(5)

,genres,original_language,original_title,overview,popularity,cast,crew,keywords
2767,"[Music, Drama]",en,54,"[Shane,, a, Jersey, boy, with, big, dreams,, c...",11.880899,"[ShaneO'Shea, AnitaRandazzo, GregRandazzo, Ste...",[MarkChristopher],"[newyork, sex, nightclub, money, drug, disco]"
2845,[Drama],en,Philomena,"[A, woman, searches, for, her, adult, son,, wh...",29.019504,"[Philomena, MartinSixsmith, YoungPhilomena, Ma...",[StephenFrears],"[mother, washingtond.c., journalist, adoption,..."
3536,"[Drama, Romance]",en,Iris,"[True, story, of, the, lifelong, romance, betw...",2.714043,"[IrisMurdoch, JohnBayley, YoungIrisMurdoch, Yo...",[RichardEyre],"[basedonnovel, newlove, loveofone'slife, retir..."
4146,[Comedy],en,Bananas,"[When, a, bumbling, New, Yorker, is, dumped, b...",5.941852,"[FieldingMellish, Nancy, GeneralEmilioM.Vargas...",[WoodyAllen],"[revolution, politicalactivism, loser]"
838,"[ScienceFiction, Action, Horror]",en,Alien³,"[After, escaping, with, Newt, and, Hicks, from...",45.856409,"[Ripley, Dillon, Clemens, David, Aaron, Golic,...",[DavidFincher],"[prison, android, spacecraft, spacemarine, imp..."

In [37]:
#Merging similar type conumn to one catagories.
merge_dataset['tags'] = merge_dataset['overview'] + merge_dataset['genres'] + merge_dataset['keywords']  + merge_dataset['cast'] + merge_dataset['crew']
merge_dataset[["movie_id",'title']] = credit[["movie_id",'title']]

In [38]:
merge_dataset.head(2)

,genres,original_language,original_title,overview,popularity,cast,crew,keywords,tags,movie_id,title
0,"[Action, Adventure, Fantasy, ScienceFiction]",en,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",150.437577,"[JakeSully, Neytiri, Dr.GraceAugustine, Col.Qu...",[JamesCameron],"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",19995.0,Avatar
1,"[Adventure, Fantasy, Action]",en,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",139.082615,"[CaptainJackSparrow, WillTurner, ElizabethSwan...",[GoreVerbinski],"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",285.0,Pirates of the Caribbean: At World's End

In [39]:
new_df = merge_dataset[["movie_id",'title','tags']]

In [40]:
new_df.dropna(inplace=True)

D:\temp\ipykernel_2520\1925939579.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.dropna(inplace=True)

In [41]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))
# new_df['tags'] = new_df['tags'].apply(lambda x: x.replace(" ",""))

D:\temp\ipykernel_2520\1807412961.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [42]:
new_df.head()

,movie_id,title,tags
0,19995.0,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285.0,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647.0,Spectre,A cryptic message from Bond’s past sends him o...
3,49026.0,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529.0,John Carter,"John Carter is a war-weary, former military ca..."

In [43]:
new_df.isnull().sum()

movie_id    0
title       0
tags        0
dtype: int64

In [44]:
# Converting tages in lower case
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

D:\temp\ipykernel_2520\2330831129.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [45]:
new_df['tags'][0]

"in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d jakesully neytiri dr.graceaugustine col.quaritch trudychacon selfridge normspellman moat eytukan tsu'tey dr.maxpatel lylewainfleet privatefike cryovaultmedtech venturestarcrewchief lockuptrooper shuttlepilot shuttleco-pilot shuttlecrewchief tractoroperator/troupe dragongunshippilot dragongunshipgunner dragongunshipnavigator suit#1 suit#2 ambientroomtech ambientroomtech/troupe horseclanleader linkroomtech basketballavatar/troupe basketballavatar na'vichild troupe troupe troupe troupe troupe troupe troupe troupe troupe troupe troupe troupe opcenterstaff opcenterstaff opcenterstaff opcenterstaff opcenterstaff opcenterdutyofficer opcenterstaff dancer dancer dancer dancer dancer dancer dancer dancer dancer miningchief(uncredited) veteranminer(uncredited) richard(uncredited) nav'i(uncredited) trooper(uncredited) trooper(uncredited) groundtechnician(uncredited) flightcrewmechanic(uncredited) samsonpilot trooper(uncredited) banshee(uncredited) soldier(uncredited) blasttechnician(uncredited) vindumraah(uncredited) hero(uncredited) opscentreworker(uncredited) engineer(uncredited) col.quaritch'smechsuit(uncredited) femalemarine(uncredited) ikranclanleader(uncredited) geologist(uncredited) na'vi(uncredited) ambientroomtech/troupe jamescameron"

In [46]:
new_df.sample(4)

,movie_id,title,tags
3085,9613.0,Spider,egyptologist erica baron finds more than she b...
2895,12479.0,Breakfast of Champions,the story of a woman who loves her dog more th...
315,1734.0,The Mummy Returns,"rick and evelyn o'connell, along with their 8 ..."
1414,11622.0,Blast from the Past,ten years after a band of mercenaries first ba...

In [47]:
import nltk
from nltk.stem import PorterStemmer

In [48]:
ps = PorterStemmer()

In [49]:
'''
Our column contain so many word that same meaning but different speling so we make function for
that word we identify that word and ake same spelling of the word. 
'''
def stems(text):
    l=[]
    for i in text.split():
        l.append(ps.stem(i))
    return " ".join(l)

In [50]:
new_df['tags'] = new_df['tags'].apply(stems)

D:\temp\ipykernel_2520\3973021881.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stems)

In [51]:
new_df.head(5)

,movie_id,title,tags
0,19995.0,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285.0,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647.0,Spectre,a cryptic messag from bond’ past send him on a...
3,49026.0,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529.0,John Carter,"john carter is a war-weary, former militari ca..."

In [52]:
from sklearn.feature_extraction.text import CountVectorizer

In [53]:
cv = CountVectorizer(max_features=5000,stop_words='english')

In [54]:
vector = cv.fit_transform(new_df['tags']).toarray()

In [55]:
vector.shape

(4800, 5000)

In [56]:
from sklearn.metrics.pairwise import cosine_similarity

In [57]:
similarity = cosine_similarity(vector)

In [58]:
similarity.shape

(4800, 4800)

In [59]:
def recommend(movie):
    index = new_df[new_df['title']==movie].index[0]
    distance = sorted(list(enumerate(similarity[index])),reverse=True,key=lambda x:x[1])
    for i in distance[1:6]:
        print(new_df.iloc[i[0]].title)

In [60]:
recommend("Kick-Ass")

Spider-Man
Closer to the Moon
American Gangster
Escape from Tomorrow
Disturbing Behavior

In [61]:
import pickle as pk

In [62]:
pk.dump(new_df, open("code/movie_list.pkl", 'wb'))
pk.dump(similarity, open("code/similarity.pkl", 'wb'))
print("Doe")

Doe

In [63]:
with open('code/movie_list.pkl', 'rb') as f:
    x = pk.load(f)